name: project_zero
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  get_it: ^7.6.7
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  dio: ^5.4.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  hive_flutter: ^1.1.0
  retrofit: ^4.1.0
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  retrofit_generator:

flutter:

  uses-material-design: true

  assets:
    - config/app_config.json

