// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMkcnnf8QZxNAwoZbbyeLW-t9ZpLlFKxQ',
    appId: '1:761113401884:web:6a805f2a4faf1a7c9e9dd9',
    messagingSenderId: '761113401884',
    projectId: 'projectzero-41f87',
    authDomain: 'projectzero-41f87.firebaseapp.com',
    storageBucket: 'projectzero-41f87.appspot.com',
    measurementId: 'G-H9T9ZQ7572',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTDMv1VLodIiOOi-9XfMWZGUI8Tdm71yA',
    appId: '1:761113401884:android:35ded3ecbb8a1b769e9dd9',
    messagingSenderId: '761113401884',
    projectId: 'projectzero-41f87',
    storageBucket: 'projectzero-41f87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2lkuVsPiYkys_nD6ZYWPsPp-rJaqxPoU',
    appId: '1:761113401884:ios:0388ceb4668025299e9dd9',
    messagingSenderId: '761113401884',
    projectId: 'projectzero-41f87',
    storageBucket: 'projectzero-41f87.appspot.com',
    iosBundleId: 'com.example.project.zero.projectZero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2lkuVsPiYkys_nD6ZYWPsPp-rJaqxPoU',
    appId: '1:761113401884:ios:397a456507168a4a9e9dd9',
    messagingSenderId: '761113401884',
    projectId: 'projectzero-41f87',
    storageBucket: 'projectzero-41f87.appspot.com',
    iosBundleId: 'com.example.project.zero.projectZero.RunnerTests',
  );
}
